version: "3.8"

services:
  db:
    image: postgres
    container_name: database
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - datascience
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../:/data
    init: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    networks:
      - datascience

volumes:
  db-data:
    name: db-data

networks:
  datascience:
    name: datascience
